runtime: python39
api_version: 1
c: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: loan.app
  
libraries:
  - name: ssl
    version: latest


runtime: python39
service: loan_pred
# instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /images
  static_dir: static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto